services:
  observex-db:
    image: postgres:16-alpine
    container_name: observex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: observex
      POSTGRES_PASSWORD: observex_secret
      POSTGRES_DB: observex
    ports:
      - "5432:5432"
    volumes:
      - observex_pgdata:/var/lib/postgresql/data

volumes:
  observex_pgdata:
